language: python
python:
  - "2.7"
install:
  - pip install -r server/environments/requirements.txt
  - pip install -r server/environments/requirements-test.txt
  - pip install coveralls
script:
  - py.test --cov=server
after_success:
  - coveralls
script:
  - cd client
  - npm install
  - cd ..